# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Lab3/tbird.xdc

# IP: ip/clk_gen/clk_gen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_gen || ORIG_REF_NAME==clk_gen} -quiet] -quiet
